In [1]:
import numpy as np
from scipy.optimize import minimize

In [2]:
def helical_valley(x):
    t = np.arctan2(x[1], x[0]) / (2 * np.pi)
    z = x[2]
    return 100 * (z - 10 * t) ** 2 + (np.sqrt(x[0] ** 2 + x[1] ** 2) - 1) ** 2 + z ** 2

In [3]:
x0 = np.array([-1.0, 0.0, 0.0])
iterations=[]
def callback(cb):
    iterations.append(cb)
result = minimize(helical_valley, x0, method='Powell',callback=callback)

print("Optimal solution:", result.x)
print("Optimal function value:", result.fun)
print("Iterations:",len(iterations))

Optimal solution: [1. 0. 0.]
Optimal function value: 0.0
Iterations: 2


In [4]:
def partial_derivative_x(x, y, z):
    return (2000 * y * (z - 10 * np.arctan2(y, x))) / (x**2 + y**2) + (2 * (np.sqrt(x**2 + y**2) - 1) * x) / np.sqrt(x**2 + y**2)

def partial_derivative_y(x, y, z):
    return (-2000 * (z - 10 * np.arctan2(y, x)) * x) / (x**2 + y**2) + (2 * (np.sqrt(x**2 + y**2) - 1) * y) / np.sqrt(x**2 + y**2)

def partial_derivative_z(x, y, z):
    return 200 * (z - 10 * np.arctan2(y, x)) + 2 * z

def gradient(x,y,z):
    dx=partial_derivative_x(x,y,z)
    dy=partial_derivative_y(x,y,z)
    dz=partial_derivative_z(x,y,z)
    return dx,dy,dz

In [5]:
gradient(1,1,1)

(-6853.395847536856, 6854.56742041211, -1368.7963267948965)

In [6]:
import sympy as sp

# Define the variables
x, y, z = sp.symbols('x y z')

# Define the function
f = 100 * (z - 10 * sp.atan2(y, x))**2 + (sp.sqrt(x**2 + y**2) - 1)**2 + z**2

# Compute the gradient
gradient = [sp.diff(f, var) for var in (x, y, z)]

# Display the gradient
print("Gradient:", gradient)


Gradient: [2*x*(sqrt(x**2 + y**2) - 1)/sqrt(x**2 + y**2) + 2000*y*(z - 10*atan2(y, x))/(x**2 + y**2), -2000*x*(z - 10*atan2(y, x))/(x**2 + y**2) + 2*y*(sqrt(x**2 + y**2) - 1)/sqrt(x**2 + y**2), 202*z - 2000*atan2(y, x)]


In [7]:
point = {x: 1, y: 1, z: 1}
evaluated_gradient = [expr.subs(point) for expr in gradient]
print(evaluated_gradient)

[-2500*pi + sqrt(2)*(-1 + sqrt(2)) + 1000, -1000 + sqrt(2)*(-1 + sqrt(2)) + 2500*pi, 202 - 500*pi]


In [8]:
from sympy import symbols, sqrt, atan2, diff

# Define variables
x, y, z = symbols('x y z')

# Define the function
f = 100 * (z - 10 * atan2(y, x))**2 + (sqrt(x**2 + y**2) - 1)**2 + z**2

# Calculate partial derivatives
df_dx = diff(f, x)
df_dy = diff(f, y)
df_dz = diff(f, z)

# Calculate second partial derivatives
d2f_dx2 = diff(df_dx, x)
d2f_dy2 = diff(df_dy, y)
d2f_dz2 = diff(df_dz, z)

d2f_dxdy = diff(df_dx, y)
d2f_dxdz = diff(df_dx, z)
d2f_dydz = diff(df_dy, z)

# Print the derivatives
print("Partial derivative with respect to x:", df_dx)
print("Partial derivative with respect to y:", df_dy)
print("Partial derivative with respect to z:", df_dz)

print("\nSecond partial derivative with respect to x^2:", d2f_dx2)
print("Second partial derivative with respect to y^2:", d2f_dy2)
print("Second partial derivative with respect to z^2:", d2f_dz2)

print("\nSecond partial derivative with respect to x and y:", d2f_dxdy)
print("Second partial derivative with respect to x and z:", d2f_dxdz)
print("Second partial derivative with respect to y and z:", d2f_dydz)


Partial derivative with respect to x: 2*x*(sqrt(x**2 + y**2) - 1)/sqrt(x**2 + y**2) + 2000*y*(z - 10*atan2(y, x))/(x**2 + y**2)
Partial derivative with respect to y: -2000*x*(z - 10*atan2(y, x))/(x**2 + y**2) + 2*y*(sqrt(x**2 + y**2) - 1)/sqrt(x**2 + y**2)
Partial derivative with respect to z: 202*z - 2000*atan2(y, x)

Second partial derivative with respect to x^2: 2*x**2/(x**2 + y**2) - 2*x**2*(sqrt(x**2 + y**2) - 1)/(x**2 + y**2)**(3/2) - 4000*x*y*(z - 10*atan2(y, x))/(x**2 + y**2)**2 + 20000*y**2/(x**2 + y**2)**2 + 2*(sqrt(x**2 + y**2) - 1)/sqrt(x**2 + y**2)
Second partial derivative with respect to y^2: 20000*x**2/(x**2 + y**2)**2 + 4000*x*y*(z - 10*atan2(y, x))/(x**2 + y**2)**2 + 2*y**2/(x**2 + y**2) - 2*y**2*(sqrt(x**2 + y**2) - 1)/(x**2 + y**2)**(3/2) + 2*(sqrt(x**2 + y**2) - 1)/sqrt(x**2 + y**2)
Second partial derivative with respect to z^2: 202

Second partial derivative with respect to x and y: 2*x*y/(x**2 + y**2) - 20000*x*y/(x**2 + y**2)**2 - 2*x*y*(sqrt(x**2 + y**2) - 1)/(

In [9]:
def biggs_exp6_function(x, t, y):
    return np.sum((np.exp(-t * x) - y)**2)

In [10]:
initial_guess = np.array([1.0,2.0,1.0,1.0,1.0,1.0])
iterations=[]
def callback(cb):
    iterations.append(cb)
t_values = np.array([10*(i+1) for i in range(len(initial_guess))])
y_values = np.exp(-t_values) -5*np.exp(-10*t_values)+3*np.exp(-4*t_values)
# Minimize the Biggs EXP6 function
result = minimize(biggs_exp6_function, initial_guess, args=(t_values, y_values), method='BFGS',callback=callback)
print("Optimal solution:", result.x)
print("Optimal function value:", result.fun)
print("Iterarions:",len(iterations))

Optimal solution: [1. 2. 1. 1. 1. 1.]
Optimal function value: 4.248354237778568e-18
Iterarions: 0


In [11]:
def gradient(x,t,y):
    return -2*t*(np.exp(-t*x)-y)*np.exp(-t*x)

In [12]:
gradient(initial_guess,t_values,y_values)

array([ 1.15734879e-20,  3.50260430e-25, -0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00])

In [13]:
def hessian(x,t,y):
    return np.diag(2*t*(1+(np.exp(-t*x)-y)*(np.exp(-t*x))))

In [14]:
hessian(initial_guess,t_values,y_values)

array([[ 20.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  40.,   0.,   0.,   0.,   0.],
       [  0.,   0.,  60.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  80.,   0.,   0.],
       [  0.,   0.,   0.,   0., 100.,   0.],
       [  0.,   0.,   0.,   0.,   0., 120.]])

In [15]:
import numpy as np

def gaussian_function(x):
    """
    x: numpy array, representing the vector of variables
    A: numpy array, representing the positive definite matrix
    """
    ys=[0.0009, 0.0044, 0.0175, 0.0540, 0.1295, 0.2420, 0.3521]
    ans=0
    for i,y in enumerate(ys):
        t1=(8-i+1)/2
        t2=(8-(15-i))/2
        exponent1 = (-x[1]*(t1-x[2])**2)/2
        exponent2 = (-x[1]*(t2-x[2])**2)/2
        ans+= (x[0]*np.exp(exponent1)-y)**2
        ans+=(x[0]*np.exp(exponent2)-y)**2
    exponentf = (-x[1]*(x[2])**2)/2
    ans+=(x[0]*np.exp(exponent2)-0.3989)**2
    return ans

# Example usage
variables= np.array([0.4,1,0])  # Example vector of variables

result = gaussian_function(variables)
print(f"The value of the Gaussian function is: {result}")
from scipy.optimize import minimize

# Define the negative of the Gaussian function (since minimize finds the minimum)
negative_gaussian = lambda x: gaussian_function(x)

# Initial guess
initial_guess = np.array([0.4,1.0,0.0])
iterations=[]
# Minimize the negative Gaussian function
result = minimize(negative_gaussian, initial_guess, method='BFGS',callback=callback)

# Print the result
print("Optimal x:", result.x)
print("Minimum value of the function:", result.fun)
print("Iterations:",len(iterations))

The value of the Gaussian function is: 0.10207049569085339
Optimal x: [0.52388083 0.7058404  0.48088152]
Minimum value of the function: 0.0014489424560909297
Iterations: 11


In [16]:
def gaussian_gradient(x):
    ys = [0.0009, 0.0044, 0.0175, 0.0540, 0.1295, 0.2420, 0.3521]
    gradient = np.zeros_like(x)

    for i, y in enumerate(ys):
        t1 = (8 - i + 1) / 2
        t2 = (8 - (15 - i)) / 2
        exponent1 = (-x[1] * (t1 - x[2]) ** 2) / 2
        exponent2 = (-x[1] * (t2 - x[2]) ** 2) / 2

        # Partial derivative with respect to x[0]
        gradient[0] += 2 * (x[0] * np.exp(exponent1) - y) * np.exp(exponent1)
        gradient[0] += 2 * (x[0] * np.exp(exponent2) - y) * np.exp(exponent2)

        # Partial derivative with respect to x[1]
        gradient[1] += 2 * x[0] * (x[2] ** 2) * (x[0] * np.exp(exponent2) - 0.3989) * np.exp(exponent2)

        # Partial derivative with respect to x[2]
        gradient[2] += 2 * x[0] * x[1] * (x[0] * np.exp(exponent2) - 0.3989) * x[2] * np.exp(exponent2)

    return gradient


In [17]:
def gaussian_hessian(x):
    ys = [0.0009, 0.0044, 0.0175, 0.0540, 0.1295, 0.2420, 0.3521]
    hessian = np.zeros((len(x), len(x)))

    for i, y in enumerate(ys):
        t1 = (8 - i + 1) / 2
        t2 = (8 - (15 - i)) / 2
        exponent1 = (-x[1] * (t1 - x[2]) ** 2) / 2
        exponent2 = (-x[1] * (t2 - x[2]) ** 2) / 2

        # Second partial derivative with respect to x[0]
        hessian[0, 0] += 2 * np.exp(exponent1) ** 2 + 2 * np.exp(exponent2) ** 2

        # Second partial derivative with respect to x[1]
        hessian[1, 1] += 2 * (x[0] * (x[2] ** 2) * np.exp(exponent2)) ** 2

        # Second partial derivative with respect to x[2]
        hessian[2, 2] += 2 * (x[0] * x[1] * x[2] * np.exp(exponent2)) ** 2

        # Cross derivatives
        hessian[0, 1] += 4 * x[0] * x[1] * (x[2] ** 2) * np.exp(exponent2) * np.exp(exponent2)
        hessian[1, 0] = hessian[0, 1]

        hessian[0, 2] += 4 * x[0] * x[1] * x[2] * (x[0] * np.exp(exponent2) - 0.3989) * np.exp(exponent2)
        hessian[2, 0] = hessian[0, 2]

        hessian[1, 2] += 2 * x[0] * (x[0] * np.exp(exponent2) - 0.3989) * (2 * x[1] * x[2] ** 2) * np.exp(exponent2)
        hessian[2, 1] = hessian[1, 2]

    return hessian

In [18]:
def three_dimensional_box(x):
    t = 0.1 * np.arange(1, 11)
    return np.linalg.norm(np.exp(-t * x[0]) - np.exp(-t *  x[1]) -  x[2] * (np.exp(-t) - np.exp(-10 * t)))



In [91]:
def three_dimensional_box_gradient(x):
    t = 0.1 * np.arange(1, 11)
    gradient = np.zeros_like(x)

    for i in range(len(t)):
        exp_term = np.exp(-t[i] * x[0])
        gradient[0] += 2 * (exp_term - np.exp(-t[i] * x[1]) - x[2] * t[i] * exp_term)
        gradient[1] -= 2 * t[i] * np.exp(-t[i] * x[1]) * (exp_term - x[2] * t[i] * exp_term)
        gradient[2] -= 2 * (np.exp(-t[i]) - np.exp(-10 * t[i])) * exp_term

    return gradient

In [90]:
def three_dimensional_box_hessian(x, epsilon=1e-5):
    n = len(x)
    hessian = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            x_plus_eps = x.copy()
            x_plus_eps[i] += epsilon
            x_plus_eps[j] += epsilon
            x_minus_eps = x.copy()
            x_minus_eps[i] -= epsilon
            x_minus_eps[j] -= epsilon

            hessian[i, j] = (three_dimensional_box_gradient(x_plus_eps)[j] - three_dimensional_box_gradient(x_minus_eps)[j]) / (2 * epsilon)

    return hessian

In [19]:
x_test, y_test, z_test = 0, 10, 20

result = three_dimensional_box([x_test, y_test, z_test])
print(f"The value of the Three-Dimensional Box Function is: {result}")

The value of the Three-Dimensional Box Function is: 32.11158374495718


In [20]:
initial_guess = np.ones(3)*10
iterations=[]
# Minimize the Three-Dimensional Box Function
result = minimize(three_dimensional_box, initial_guess, method='BFGS',callback=callback)

# Print the result
print("Optimal x:", result.x)
print("Minimum value of the function:", result.fun)
print("iterations:",len(iterations))

Optimal x: [1.00035547e+01 1.00035551e+01 2.03012288e-08]
Minimum value of the function: 2.6852718877011665e-08
iterations: 21


In [23]:
hessian_three_dimensional_box([x_test, y_test, z_test])

array([[ 356,   40,    0],
       [  40, 2356,    0],
       [   0,    0,    2]])

In [24]:
def variably_dimensioned_function(x):
    n = len(x)
    result = np.empty(n+2)

    # f1 to fn
    result[:n] = x - 1

    # fn+1
    result[n] = np.sum(np.arange(1, n+1) * (x - 1))

    # fn+2
    result[n+1] = np.sum(np.arange(1, n+1) * (x - 1))**2

    return np.linalg.norm(result)

# Example usage
n=5
x_values = np.array([1-1/j for j in range(1,n+1)])  # Replace with your specific values

result_vector = variably_dimensioned_function(x_values)
print("Vector of f(x):", result_vector)


Vector of f(x): 25.523785203435466


In [25]:
initial_guess = x_values
iterations=[]
result = minimize(variably_dimensioned_function, initial_guess, method='BFGS',callback=callback)

# Print the result
print("Optimal x:", result.x)
print("Minimum value of the function:", result.fun)
print("Iterations:",len(iterations))

Optimal x: [1.         1.00000003 1.00000001 1.00000001 0.99999997]
Minimum value of the function: 4.4519732194048033e-08
Iterations: 34


In [94]:
def variably_dimensioned_function_gradient(x):
    n = len(x)
    gradient = np.zeros_like(x)

    # Partial derivatives for f1 to fn
    gradient[:n] = 2 * (x - 1)

    # Partial derivative for fn+1
    gradient[n] = 2 * np.sum(np.arange(1, n+1) * (x - 1))

    # Partial derivative for fn+2
    gradient[n+1] = 2 * np.sum(np.arange(1, n+1) * (x - 1)) * np.sum(np.arange(1, n+1) * (x - 1))

    return gradient

In [95]:
gradient_variably(np.array([ 3.03663297e-06,1.50143993e-06,4.70538704e-06,-2.74750368e-06]))

array([ 6.07326594e-06,  3.00287986e-06,  9.41077408e-06, -5.49500736e-06])

In [ ]:
def variably_dimensioned_function_hessian(x, epsilon=1e-5):
    n = len(x)
    hessian = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            x_plus_eps = x.copy()
            x_plus_eps[i] += epsilon
            x_plus_eps[j] += epsilon
            x_minus_eps = x.copy()
            x_minus_eps[i] -= epsilon
            x_minus_eps[j] -= epsilon

            hessian[i, j] = (variably_dimensioned_function_gradient(x_plus_eps)[j] - variably_dimensioned_function_gradient(x_minus_eps)[j]) / (2 * epsilon)

    return hessian


In [30]:
def watson_function(x):
    n = len(x)
    result = 0
    ans=np.zeros(31)
    for i in range(1, 30):
        a1=0
        a2=0
        t=i/29
        for j in range(1,n):
            a1+=(j)*x[j]*t**(j-1)
        for j in range(n):
            a2+=(x[j]*t**j)**2
        ans[i-1]=a1-a2-1
    ans[-2]=x[0]
    ans[-1]=x[1]+x[0]**2 -1
    return np.linalg.norm(ans)


$$\frac{\partial f}{\partial x_{i-1}}=2\left(x_{i-1}-1\right)x_{i-1}\left(1-e^{-x_{i-1}^2}\right)+\frac{20\:x_{i-1}}{\sqrt{i}}\cdot \left(\frac{\:x_{i-1}}{\sqrt{i}}-e^{^2\frac{-x_{i-1}}{\sqrt{\left(i\right)}}}\right)e^{^2\frac{-x_{i-1}}{\sqrt{\left(i\right)}}}$$

In [31]:
def watson_gradient(x):
    n = len(x)
    gradient = np.zeros(n)
    ans = np.zeros(31)

    for i in range(1, 30):
        a1 = 0
        a2 = 0
        t = i / 29
        for j in range(1, n):
            a1 += (j) * t**(j-1)
        for j in range(n):
            a2 += 2 * j * x[j] * t**(j-1)
        ans[i-1] = a1 - a2

    ans[-2] = 1
    ans[-1] = 2 * x[0]

    for i in range(n):
        gradient[i] = np.sum(ans * i * x[i] * np.arange(1, 31) / 29)

    return gradient


In [98]:
def watson_hessian(x, epsilon=1e-5):
    n = len(x)
    hessian = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            x_plus_eps = x.copy()
            x_plus_eps[i] += epsilon
            x_plus_eps[j] += epsilon
            x_minus_eps = x.copy()
            x_minus_eps[i] -= epsilon
            x_minus_eps[j] -= epsilon

            hessian[i, j] = (watson_gradient(x_plus_eps)[j] - watson_gradient(x_minus_eps)[j]) / (2 * epsilon)

    return hessian

In [99]:
# Example usage
dimension = 6
variables = np.random.rand(dimension)

result = watson_function(variables)

from scipy.optimize import minimize

# Initial guess
initial_guess = np.zeros(dimension)

# Minimize the Watson function
result = minimize(watson_function, initial_guess, method='BFGS')

print("Optimal x:", result.x)
print("Minimum value of the function:", result.fun)

Optimal x: [-1.06312021e-08  9.97966220e-01  1.43529299e-02  3.16885350e-01
 -3.19036044e-02  4.94903016e-02]
Minimum value of the function: 0.006453858327920113


In [100]:
watson_hessian(np.array([0.65494518, 0.85254106, 0.98749282, 1.0909896, 0.]))

array([[31.28672703, 10.82000434,  9.16170426,  8.41146583,  0.        ],
       [15.64336353, 21.64000866,  9.16170426,  8.41146583,  0.        ],
       [15.64336353, 10.82000434, 18.32340851,  8.41146583,  0.        ],
       [15.64336353, 10.82000434,  9.16170426, 16.82293166,  0.        ],
       [15.64336353, 10.82000434,  9.16170426,  8.41146583,  0.        ]])

In [35]:
watson_gradient(np.array([0.65494518, 0.85254106, 0.98749282, 1.0909896, 0.]))

array([-0.12562862, -0.0959441 , -0.01129189,  0.10207429,  0.        ])

In [36]:
def penalty_function_I(x):
    """
    x: numpy array, representing the vector of variables
    constraints: list of constraint functions
    """
    a=10e-5
    n=len(x)
    ans=np.zeros(n+1)
    ans[:n] =a*x-1
    ans[-1]=np.linalg.norm(x)**2-1/4
    
    return np.linalg.norm(ans)**2

# Example usage with a simple constraint

initial_guess = np.random.rand(dimension)

In [ ]:
def penalty_function_I_gradient(x):
    a = 1e-5
    n = len(x)
    gradient = np.zeros_like(x)

    gradient[:n] = 2 * a * (a * x - 1)

    gradient[-1] = 2 * np.linalg.norm(x) * np.sum(x)

    return gradient

In [ ]:
def penalty_function_I_hessian(x, epsilon=1e-5):
    n = len(x)
    hessian = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            x_plus_eps = x.copy()
            x_plus_eps[i] += epsilon
            x_plus_eps[j] += epsilon
            x_minus_eps = x.copy()
            x_minus_eps[i] -= epsilon
            x_minus_eps[j] -= epsilon

            hessian[i, j] = (penalty_function_I_gradient(x_plus_eps)[j] - penalty_function_I_gradient(x_minus_eps)[j]) / (2 * epsilon)

    return hessian

In [37]:
penalty_function_I(initial_guess)

14.245214502155747

In [38]:
# Minimize the Watson function
initial_guess=np.array(range(1,11))
result = minimize(penalty_function_I, initial_guess, method='BFGS')

print("Optimal x:", result.x)
print("Minimum value of the function:", result.fun)

Optimal x: [0.16000229 0.1580955  0.15681293 0.15673907 0.1580507  0.15754714
 0.16227176 0.15465012 0.15931135 0.1585308 ]
Minimum value of the function: 9.999683699006326


In [39]:
# Minimize the Watson function
result = minimize(lambda x: penalty_function_I(x), initial_guess, method='BFGS')

print("Optimal x:", result.x)
print("Minimum value of the function:", result.fun)

Optimal x: [0.16000229 0.1580955  0.15681293 0.15673907 0.1580507  0.15754714
 0.16227176 0.15465012 0.15931135 0.1585308 ]
Minimum value of the function: 9.999683699006326


In [42]:
def penalty_function_II(x):
    """
    x: numpy array, representing the vector of variables
    constraints: list of constraint functions
    """
    a=10e-5
    n=len(x)
    
    ans=np.zeros(2*n)
    ans[0]=x[0]-0.2
    y1=np.array([np.exp((i+1)/10)-np.exp((i)/10) for i in range(n-1)])
    y2=np.array([np.exp((i+1)/10) for i in range(n-1)])
    ans[1:n] =a**0.5*(np.exp(x[1:]/10)+np.exp(x[:n-1]/10)-y1)
    ans[n:-1] =a**0.5*(np.exp(x[1:]/10)-y2)
    ans[-1]=np.sum([((n-j)*x[j]**2) for j in range(n)])
    
    return np.linalg.norm(ans)**2

In [102]:
def penalty_function_II_gradient(x):
    a = 1e-5
    n = len(x)
    gradient = np.zeros_like(x)
    
    # Partial derivative for x[0]
    gradient[0] = 2 * (x[0] - 0.2) * (1 + a * x[0])

    # Partial derivatives for x[1] to x[n-1]
    gradient[1:n] = 2 * a * (np.exp(x[1:]/10) + np.exp(x[:n-1]/10) - np.array([np.exp((i+1)/10) - np.exp((i)/10) for i in range(n-1)]))

    # Partial derivatives for x[n] to x[2n-1]
    gradient[n:-1] = 2 * a * (np.exp(x[1:]/10) - np.array([np.exp((i+1)/10) for i in range(n-1)]))

    # Partial derivative for x[2n]
    gradient[-1] = 2 * np.sum([(n-j) * x[j] for j in range(n)])

    return gradient

In [103]:
def penalty_function_II_hessian(x, epsilon=1e-5):
    n = len(x)
    hessian = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            x_plus_eps = x.copy()
            x_plus_eps[i] += epsilon
            x_plus_eps[j] += epsilon
            x_minus_eps = x.copy()
            x_minus_eps[i] -= epsilon
            x_minus_eps[j] -= epsilon

            hessian[i, j] = (penalty_function_II_gradient(x_plus_eps)[j] - penalty_function_II_gradient(x_minus_eps)[j]) / (2 * epsilon)

    return hessian

In [43]:
# Initial guess
dimension=4
initial_guess = np.ones(dimension)/2
iteration=[]
# Minimize the Brown Badly Scaled Function
result = minimize(penalty_function_II, initial_guess, method='BFGS',callback=callback)
print("Optimal x:", result.x)
print("Minimum value of the function:", result.fun)
print("Iterations:",len(iterations))

Optimal x: [ 1.29875272e-01 -8.82752006e-05 -1.27193508e-04 -1.10731286e-04]
Minimum value of the function: 0.010557098048339484
Iterations: 49


In [44]:
def brown_badly_scaled(x):
    n = len(x)
    result = 0


    term1 = x[0] -1e6
    term2 = x[1] -2e-6
    term3 = x[0]*x[1] -2
    result += term1**2+ term2**2 +term3**2

    return result

In [45]:
# Initial guess
dimension=2
initial_guess = np.ones(dimension)
iterations=[]
# Minimize the Brown Badly Scaled Function
result = minimize(brown_badly_scaled, initial_guess, method='BFGS',callback=callback)



print("Optimal solution:", result.x)
print("Optimal function value:", result.fun)
print("Iterations:",len(iterations))

Optimal solution: [1.00000000e+06 1.99254942e-06]
Optimal function value: 5.551114377728232e-05
Iterations: 14


In [46]:
def gradient_brown_badly_scaled(x):
    n = len(x)
    gradient = np.zeros_like(x, dtype=float)

    for i in range(n-1):
        term1 = 2 * x[i] * (x[i+1]**2)**(x[i]**2) * np.log(x[i]**2) * (x[i]**2 + 1)
        term2 = 2 * x[i+1] * (x[i]**2)**(x[i+1]**2) * np.log(x[i+1]**2) * (x[i+1]**2 + 1)

        gradient[i] += term1def brown_badly_scaled_gradient(x):
    n = len(x)
    gradient = np.zeros_like(x)

    gradient[0] = 2 * (x[0] - 1e6) * (1 + x[0] * x[1])
    gradient[1] = 2 * (x[1] - 2e-6) * (x[0] + x[1] * x[0])

    return gradient
        gradient[i+1] += term2

    return gradient

In [47]:
gradient_brown_badly_scaled([1.95848211e-06,1.79366035e-06,1.45346821e-06,-3.39815933e-07,2.01403015e-06])

array([-1.02963991e-04, -1.89858979e-04, -1.56295018e-04,  4.04920907e-05,
       -1.05659025e-04])

In [48]:
def brown_badly_scaled_hessian(x, epsilon=1e-5):
    n = len(x)
    hessian = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            x_plus_eps = x.copy()
            x_plus_eps[i] += epsilon
            x_plus_eps[j] += epsilon
            x_minus_eps = x.copy()
            x_minus_eps[i] -= epsilon
            x_minus_eps[j] -= epsilon

            hessian[i, j] = (brown_badly_scaled_gradient(x_plus_eps)[j] - brown_badly_scaled_gradient(x_minus_eps)[j]) / (2 * epsilon)

    return hessian

In [49]:
hessian_brown_badly_scaled([1.95848211e-06,1.79366035e-06,1.45346821e-06,-3.39815933e-07,2.01403015e-06])

array([[-52.57336327, -52.57336327, -52.57336327, -52.57336327,
        -52.57336327],
       [-52.92500855, -52.92500855, -52.92500855, -52.92500855,
        -52.92500855],
       [-53.76623195, -53.76623195, -53.76623195, -53.76623195,
        -53.76623195],
       [-59.57944695, -59.57944695, -59.57944695, -59.57944696,
        -59.57944695],
       [-52.46149117, -52.46149117, -52.46149117, -52.46149117,
        -52.46149117]])

In [50]:
def brown_and_dennis(x):
    n = len(x)
    m=20
    ans=np.zeros(m)
    t= np.linspace(1,20,m)/m
    ans =(x[0]+t*x[1]-np.exp(t))**2+(x[2]+x[3]*np.sin(t)-np.sin(t))**2


    return np.linalg.norm(ans)**2

In [51]:
def brown_and_dennis_gradient(x):
    n = len(x)
    m = 20
    ans = np.zeros(m)
    t = np.linspace(1, 20, m) / m

    ans = np.array([
        2 * (x[0] + t * x[1] - np.exp(t)) * x[1],
        2 * (x[0] + t * x[1] - np.exp(t)) * t,
        2 * (x[2] + x[3] * np.sin(t) - np.sin(t)) * x[3],
        2 * (x[2] + x[3] * np.sin(t) - np.sin(t)) * np.sin(t)
    ])

    gradient = np.zeros_like(x)
    gradient[0] = np.sum(ans[:m] * x[1])
    gradient[1] = np.sum(ans[:m] * (x[0] + t * x[1]))
    gradient[2] = np.sum(ans[m:] * x[3])
    gradient[3] = np.sum(ans[m:] * (x[2] + x[3] * np.sin(t)))

    return gradient

In [52]:
# Example usage
dimension = 4
variables = np.array([25, 5, -5,-1])

result = brown_and_dennis(variables)
print(f"The value of the Brown and Dennis Function is: {result}")
# Initial guess
initial_guess = variables
iterations=[]
# Minimize the Brown and Dennis Function
result = minimize(brown_and_dennis, initial_guess, method='BFGS',callback=callback)

# Print the result
print("Optimal solution:", result.x)
print("Optimal function value:", result.fun)
print("Iterations:",len(iterations))

The value of the Brown and Dennis Function is: 10016239.906752376
Optimal solution: [ 8.57717122e-01  1.74634067e+00 -1.11331063e-06  1.00000904e+00]
Optimal function value: 0.0006173214141067991
Iterations: 96


In [53]:
def brown_and_dennis_hessian(x, epsilon=1e-5):
    n = len(x)
    hessian = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            x_plus_eps = x.copy()
            x_plus_eps[i] += epsilon
            x_plus_eps[j] += epsilon
            x_minus_eps = x.copy()
            x_minus_eps[i] -= epsilon
            x_minus_eps[j] -= epsilon

            hessian[i, j] = (brown_and_dennis_gradient(x_plus_eps)[j] - brown_and_dennis_gradient(x_minus_eps)[j]) / (2 * epsilon)

    return hessian

In [54]:
def gulf_function(x, m=4):
    ans=np.zeros(m)
    t=np.array([(i+1) for i in range(m)])/100
    y=25+(-50*np.log(t))**2/3
    ans=np.exp((-abs(y*100*t*m*x[1])**x[2])/x[0])-t
    return np.linalg.norm(ans)**2

In [55]:
def gulf_function_gradient(x, m=4):
    ans = np.zeros(m)
    t = np.array([(i+1) for i in range(m)]) / 100
    y = 25 + (-50 * np.log(t))**2 / 3

    ans = np.array([
        -2 * x[1] * x[0] * x[2] * abs(y * 100 * t * m * x[1])**(x[2] - 1) * np.sign(y * 100 * t * m * x[1]) * np.exp((-abs(y * 100 * t * m * x[1])**x[2]) / x[0]),
        -2 * x[0] * abs(y * 100 * t * m * x[1])**x[2] * np.exp((-abs(y * 100 * t * m * x[1])**x[2]) / x[0]) / x[0],
        2 * abs(y * 100 * t * m * x[1])**x[2] * np.exp((-abs(y * 100 * t * m * x[1])**x[2]) / x[0]) / x[0]**2
    ])

    gradient = np.zeros_like(x)
    gradient[1] = np.sum(ans)

    return gradient

In [56]:
def gulf_function_hessian(x, epsilon=1e-5, m=4):
    n = len(x)
    hessian = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            x_plus_eps = x.copy()
            x_plus_eps[i] += epsilon
            x_plus_eps[j] += epsilon
            x_minus_eps = x.copy()
            x_minus_eps[i] -= epsilon
            x_minus_eps[j] -= epsilon

            hessian[i, j] = (gulf_function_gradient(x_plus_eps)[j] - gulf_function_gradient(x_minus_eps)[j]) / (2 * epsilon)

    return hessian

In [57]:
# Initial guess
initial_guess = np.array([5,2.5,0.15])
iterations=[]
# Minimize the Gulf Function
result = minimize(gulf_function, initial_guess, method='Powell',callback=callback)

# Print the result
print("Optimal solution:", result.x)
print("Optimal function value:", result.fun)
print("iterations:",len(iterations))

Optimal solution: [ 0.48491083 -0.10046213  0.06349683]
Optimal function value: 0.0006379152333885442
iterations: 10


In [58]:
def trigonometric_function(x):
    n=len(x)
    ans=np.zeros(n)
    for i in range(n):
        ans[i]=n-np.sum(np.cos(x))+(i+1)*(1-np.cos(x[i])) -np.sin(x[i])
    return np.linalg.norm(ans)**2

In [59]:
def trigonometric_function_gradient(x):
    n = len(x)
    ans = np.zeros(n)
    for i in range(n):
        ans[i] = 2 * (n - np.sum(np.cos(x))) * np.sin(x[i]) - (i + 1) * np.sin(x[i])
    return ans

In [60]:
def trigonometric_function_hessian(x, epsilon=1e-5):
    n = len(x)
    hessian = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            x_plus_eps = x.copy()
            x_plus_eps[i] += epsilon
            x_plus_eps[j] += epsilon
            x_minus_eps = x.copy()
            x_minus_eps[i] -= epsilon
            x_minus_eps[j] -= epsilon

            hessian[i, j] = (trigonometric_function_gradient(x_plus_eps)[j] - trigonometric_function_gradient(x_minus_eps)[j]) / (2 * epsilon)

    return hessian

In [61]:
variables=np.ones(50)/50
result = trigonometric_function(variables)
print(f"The value of the Trigonometric Function is: {result}")
iterations=[]
result = minimize(trigonometric_function, variables, method='Powell',callback=callback)

print("Optimal solution:", result.x)
print("Optimal function value:", result.fun)
print("Iterations:",len(iterations))

The value of the Trigonometric Function is: 0.0016165655783864058
Optimal solution: [0.01251834 0.01257993 0.01264239 0.01270579 0.01277008 0.01283552
 0.01290166 0.01296882 0.01303694 0.013106   0.13091753 0.01324647
 0.01331832 0.01339097 0.01346427 0.01353838 0.01361314 0.01368852
 0.0137644  0.0138406  0.01391711 0.0139937  0.01407035 0.01414638
 0.01422194 0.0142966  0.0143701  0.01444191 0.01451183 0.0145791
 0.01464336 0.01470398 0.01476035 0.01481178 0.0148576  0.01489709
 0.01492956 0.01495432 0.01497081 0.01497829 0.01497658 0.01496519
 0.01494407 0.01491295 0.01487208 0.01482166 0.01476205 0.01469371
 0.01461719 0.01453758]
Optimal function value: 0.0007811001559582129
Iterations: 6


In [64]:
def extended_rosenbrock_function(x):
    n = len(x)
    result = 0

    for i in range(n-1):
        term1 = 100 * (x[i+1] - x[i]**2)**2
        term2 = (1 - x[i])**2
        result += term1 + term2

    return result

In [65]:
import numpy as np

def extended_rosenbrock_gradient(x):
    n = len(x)
    gradient = np.zeros(n)

    for i in range(n-1):
        gradient[i] = -400 * x[i] * (x[i+1] - x[i]**2) - 2 * (1 - x[i]) + 200 * (x[i+1] - x[i]**2)
        gradient[i+1] = 200 * ( - x[i]**2)

    return gradient


In [66]:
def extended_rosenbrock_hessian(x):
    n = len(x)
    hessian = np.zeros((n, n))

    for i in range(n-1):
        hessian[i, i] = 1200 * x[i]**2 - 400 * x[i+1] + 2
        hessian[i, i+1] = hessian[i+1, i] = -400 * x[i]

    return hessian

In [67]:
dimension = 3
variables = np.array([1, 1, 1])

result = extended_rosenbrock_function(variables)
print(f"The value of the Extended Rosenbrock Function is: {result}")
iterations=[]
result = minimize(extended_rosenbrock_function, variables, method='Powell',callback=callback)

print("Optimal solution:", result.x)
print("Optimal function value:", result.fun)
print("iterations:",len(iterations))

The value of the Extended Rosenbrock Function is: 0
Optimal solution: [1. 1. 1.]
Optimal function value: 0.0
iterations: 1


In [68]:
extended_rosenbrock_gradient(result.x)

array([   0.,    0., -200.])

In [69]:
extended_rosenbrock_hessian(result.x)

array([[ 802., -400.,    0.],
       [-400.,  802., -400.],
       [   0., -400.,    0.]])

In [70]:
def extended_powell_singular_function(x):
    n = len(x)
    result = 0

    for i in range(0, n//4):
        term1 = (x[4*i-3] + 10*x[4*i-2])**2
        term2 = 5 * (x[4*i-1] - x[4*i])**2
        term3 = (x[4*i-2] - 2*x[4*i-1])**4
        term4 = 10 * (x[4*i-3] - x[4*i])**4
        result += term1 + term2 + term3 + term4

    return result

In [71]:
def extended_powell_singular_gradient(x):
    n = len(x)
    gradient = np.zeros(n)

    for i in range(n // 4):
        gradient[4*i] = 2 * (x[4*i] + 10*x[4*i+1]) + 40 * (x[4*i] - x[4*i+3])**3
        gradient[4*i+1] = 20 * (x[4*i] + 10*x[4*i+1]) + 4 * (x[4*i+1] - 2*x[4*i+2])**3
        gradient[4*i+2] = 10 * (5 * (x[4*i+2] - x[4*i+3]) - 8 * (x[4*i+1] - 2*x[4*i+2])**3)
        gradient[4*i+3] = -10 * (5 * (x[4*i+2] - x[4*i+3]) + 40 * (x[4*i] - x[4*i+3])**3)

    return gradient

In [72]:
dimension = 4
# Initial guess
initial_guess = np.ones(dimension)

# Minimize the Extended Powell Singular Function
result = minimize(extended_powell_singular_function, initial_guess, method='BFGS')

# Print the result
print("Optimal solution:", result.x)
print("Optimal function value:", result.fun)



Optimal solution: [-0.00310417  0.00156839 -0.00015684 -0.0031042 ]
Optimal function value: 6.1078478163066054e-09


In [73]:
extended_powell_singular_gradient(result.x)

array([ 0.02515948,  0.25159484,  0.14736713, -0.14736767])

In [74]:
def extended_powell_singular_hessian(x):
    n = len(x)
    hessian = np.zeros((n, n))

    for i in range(n // 4):
        hessian[4*i, 4*i] = 2 + 120 * (x[4*i] - x[4*i+3])**2
        hessian[4*i, 4*i+1] = 20
        hessian[4*i, 4*i+3] = -120 * (x[4*i] - x[4*i+3])**2

        hessian[4*i+1, 4*i] = 20
        hessian[4*i+1, 4*i+1] = 200 + 12 * (x[4*i+1] - 2*x[4*i+2])**2

        hessian[4*i+1, 4*i+2] = -24 * (x[4*i+1] - 2*x[4*i+2])**2

        hessian[4*i+2, 4*i+1] = -24 * (x[4*i+1] - 2*x[4*i+2])**2
        hessian[4*i+2, 4*i+2] = 10 - 192 * (x[4*i+1] - 2*x[4*i+2])**2
        hessian[4*i+2, 4*i+3] = -20

        hessian[4*i+3, 4*i] = -120 * (x[4*i] - x[4*i+3])**2
        hessian[4*i+3, 4*i+2] = -20
        hessian[4*i+3, 4*i+3] = 120 + 120 * (x[4*i] - x[4*i+3])**2

    return hessian

In [75]:
extended_powell_singular_hessian(result.x)

array([[ 2.00000000e+00,  2.00000000e+01,  0.00000000e+00,
        -9.16433268e-14],
       [ 2.00000000e+01,  2.00000043e+02, -8.50133944e-05,
         0.00000000e+00],
       [ 0.00000000e+00, -8.50133944e-05,  9.99931989e+00,
        -2.00000000e+01],
       [-9.16433268e-14,  0.00000000e+00, -2.00000000e+01,
         1.20000000e+02]])

In [76]:
def beale_function(X):
    x,y=X
    term1 = (1.5 - x + x*y)**2
    term2 = (2.25 - x + x*y**2)**2
    term3 = (2.625 - x + x*y**3)**2
    return term1 + term2 + term3

$$f(x, y) = (1.5 - x + xy)^2 + (2.25 - x + xy^2)^2 + (2.625 - x + xy^3)^2$$


$$ \frac{\partial f}{\partial x} = 2 \left[ (1.5 - x + xy)(-1 + y) + (2.25 - x + xy^2)(-1 + y^2) + (2.625 - x + xy^3)(-1 + y^3) \right] $$

$$ \frac{\partial f}{\partial y} = 2 \left[ (1.5 - x + xy)x + 2(2.25 - x + xy^2)xy + 3(2.625 - x + xy^3)xy^2 \right] $$


In [77]:
def beale_gradient(X):
    x, y = X
    
    df_dx = 2 * ((1.5 - x + x * y) * (-1 + y) +
                 (2.25 - x + x * y**2) * (-1 + y**2) +
                 (2.625 - x + x * y**3) * (-1 + y**3))
    
    df_dy = 2 * ((1.5 - x + x * y) * x +
                 2 * (2.25 - x + x * y**2) * x * y +
                 3 * (2.625 - x + x * y**3) * x * y**2)
    
    return (df_dx, df_dy)


In [78]:
# Initial guess
initial_guess = np.array([1.0, 1.0])

# Minimize the Beale function
result = minimize(beale_function, initial_guess, method='BFGS')

# Print the result
print("Optimal solution:", result.x)
print("Optimal function value:", result.fun)

Optimal solution: [2.99999967 0.49999991]
Optimal function value: 1.9911045053339106e-14


In [79]:
beale_gradient(result.x)

(1.1517816560634913e-08, -4.7313066920637025e-07)



$$
 \frac{\partial^2 f}{\partial x^2} = 2 \left[ (1 - y) + 2(1 - y^2) + 3(1 - y^3) \right]
$$

$$
 \frac{\partial^2 f}{\partial y^2} = 2 \left[ x^2 + 2x^2 + 6x^2y + 6x^2y^2 \right] 
 $$
 $$
 \frac{\partial^2 f}{\partial x \partial y} = \frac{\partial^2 f}{\partial y \partial x} = 2 \left[ -1 + 2xy + 3xy^2 \right] $$

In [80]:
def hessian_beale(X):
    x,y=X
    f_xx = 2 * ((1 - y) + 2 * (1 - y**2) + 3 * (1 - y**3))
    f_yy = 2 * (x**2 + 2*x**2 + 6*x**2*y + 6*x**2*y**2)
    f_xy = f_yx = 2 * (-1 + 2*x*y + 3*x*y**2)

    return np.array([[f_xx, f_xy], [f_yx, f_yy]])

In [81]:
hessian_beale(result.x)

array([[  9.25000097,   8.49999608],
       [  8.49999608, 134.99995034]])

$$f(x) = 100 \cdot (x_2 - x_1^2)^2 + (1 - x_1)^2 + 90 \cdot (x_4 - x_3^2)^2 + (1 - x_3)^2 + 10 \cdot (x_2 + x_4 - 2)^2 + \frac{1}{10} \cdot (x_2 - x_4)^2$$

In [82]:
def wood_function(x):
    term1 = 100 * (x[1] - x[0]**2)**2
    term2 = (1 - x[0])**2
    term3 = 90 * (x[3] - x[2]**2)**2
    term4 = (1 - x[2])**2
    term5 = 10 * (x[1] + x[3] - 2)**2
    term6 = (1/10) * (x[1] - x[3])**2
    return term1 + term2 + term3 + term4 + term5 + term6

$$
\nabla f(x) = \left[ -400 \cdot x_1 \cdot (x_2 - x_1^2) - 2 \cdot (1 - x_1), \, 200 \cdot (x_2 - x_1^2) + 20 \cdot (x_2 + x_4 - 2) + 0.2 \cdot (x_2 - x_4), \, -360 \cdot x_3 \cdot (x_4 - x_3^2) - 2 \cdot (1 - x_3), \, 180 \cdot (x_4 - x_3^2) + 20 \cdot (x_2 + x_4 - 2) - 0.2 \cdot (x_2 - x_4) \right]
$$

In [83]:
def wood_gradient(x):
    df_dx1 = -400 * x[0] * (x[1] - x[0]**2) - 2 * (1 - x[0])
    df_dx2 = 200 * (x[1] - x[0]**2) + 20 * (x[1] + x[3] - 2) + 0.2 * (x[1] - x[3])
    df_dx3 = -360 * x[2] * (x[3] - x[2]**2) - 2 * (1 - x[2])
    df_dx4 = 180 * (x[3] - x[2]**2) + 20 * (x[1] + x[3] - 2) - 0.2 * (x[1] - x[3])

    gradient = np.array([df_dx1, df_dx2, df_dx3, df_dx4])
    return gradient

In [84]:
# Initial guess
initial_guess = np.array([-3, -1, -3, -1])
iterations=[]
# Minimize the Wood function
result = minimize(wood_function, initial_guess, method='BFGS',callback=callback)

# Print the result
print("Optimal solution:", result.x)
print("Optimal function value:", result.fun)
print("Iterations:",len(iterations))

Optimal solution: [0.99999968 0.99999938 1.00000019 1.0000004 ]
Optimal function value: 7.954383299019438e-13
Iterations: 86


In [85]:
wood_gradient(result.x)

array([-1.11018032e-05,  7.74132193e-07, -6.29806834e-06, -7.06321285e-07])

$$
\mathbf{H}(x) = \begin{bmatrix}
1200x_1^2 - 400x_2 + 2 & -400x_1 & 0 & 0 \\
-400x_1 & 220 + 20 & 0 & 20 \\
0 & 0 & 1080x_3^2 - 360x_4 + 2 & -360x_3 \\
0 & 20 & -360x_3 & 200 + 20 - 0.2
\end{bmatrix}
$$

In [86]:
def wood_hessian(x):
    h11 = 1200 * x[0]**2 - 400 * x[1] + 2
    h12 = -400 * x[0]
    h13 = 0
    h14 = 0

    h21 = -400 * x[0]
    h22 = 220 + 20
    h23 = 0
    h24 = 20

    h31 = 0
    h32 = 0
    h33 = 1080 * x[2]**2 - 360 * x[3] + 2
    h34 = -360 * x[2]

    h41 = 0
    h42 = 20
    h43 = -360 * x[2]
    h44 = 200 + 20 - 0.2

    hessian_matrix = np.array([[h11, h12, h13, h14],
                               [h21, h22, h23, h24],
                               [h31, h32, h33, h34],
                               [h41, h42, h43, h44]])

    return hessian_matrix

In [87]:
wood_hessian(result.x)

array([[ 801.99947575, -399.99987155,    0.        ,    0.        ],
       [-399.99987155,  240.        ,    0.        ,   20.        ],
       [   0.        ,    0.        ,  722.00027047, -360.00006929],
       [   0.        ,   20.        , -360.00006929,  219.8       ]])

$$
\text{chebyquad\_function}(x) = \left( \sum_{i=1}^{n} T_i(x) \right)^2
$$ 



where $T_i(x)$  are Chebyshev polynomials of the first kind, and  is the length of the input vector $x.$

$$\nabla \text{chebyquad\_function}(x) = 2 \left( \sum_{i=1}^{n} T_i(x) \right) \sum_{i=1}^{n} \nabla T_i(x)$$

In [88]:
from numpy.polynomial import chebyshev
def chebyquad_function(x):
    n = len(x)
    coefficients = [0] * (n - 1) + [1]
    return np.linalg.norm(chebyshev.chebval(x, coefficients))

In [89]:
n=8
initial_guess = np.array([j/(n+1) for j in range(1,n+1)])
iterations=[]
# Minimize the Wood function
result = minimize(chebyquad_function, initial_guess, method='BFGS',callback=callback)

# Print the result
print("Optimal solution:", result.x)
print("Optimal function value:", result.fun)
print("Iterations:",len(iterations))

Optimal solution: [-1.29537067e-08  1.66052438e-09  4.33883736e-01  4.33883738e-01
  4.33883739e-01  7.81831475e-01  7.81831480e-01  7.81831479e-01]
Optimal function value: 1.3846731514262084e-07
Iterations: 64


In [ ]:
def chebyquad_function_gradient(x):
    n = len(x)
    coefficients = [0] * (n - 1) + [1]
    cheb_poly = chebyshev.Chebyshev(coefficients)
    
    gradient = np.zeros(n)
    for i in range(n):
        # Derivative of the Chebyshev polynomial with respect to x_i
        derivative_poly = cheb_poly.deriv(m=i)
        gradient[i] = 2 * np.inner(derivative_poly.coef, chebyshev.chebval(x, coefficients))

    return gradient

In [ ]:
def chebyquad_function_hessian(x, epsilon=1e-5):
    n = len(x)
    hessian = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            x_plus_eps = x.copy()
            x_plus_eps[i] += epsilon
            x_plus_eps[j] += epsilon
            x_minus_eps = x.copy()
            x_minus_eps[i] -= epsilon
            x_minus_eps[j] -= epsilon

            hessian[i, j] = (chebyquad_function_gradient(x_plus_eps)[j] - chebyquad_function_gradient(x_minus_eps)[j]) / (2 * epsilon)

    return hessian